version: "3"
services:
 telegraf:
  image: telegraf:1.29.4
  volumes:
   - ./telegraf.conf:/etc/telegraf/telegraf.conf
  depends_on:
   - influxdb
  links:
   - influxdb
  ports:
   - "8125:8125"
  networks:
   - teleg

 influxdb:
  image: influxdb:1.8.10
  environment: 
   - INFLUXDB_DB=influxdb
   - INFLUXDB_ADMIN_USER=admin
   - INFLUXDB_ADMIN_PASSWORD=admin
  ports:
   - "8086:8086"
  volumes:
   - ./:/imports
   - influxdb_data:/var/lib/influxdb
  networks:
   - teleg

 grafana:
  image: grafana/grafana-oss:10.3.3
  depends_on:
   - influxdb
  environment:
   - GF_SECURITY_ADMIN_USER=admin
   - GF_SECURITY_ADMIN_PASSWORD=admin
  links:
   - influxdb
  ports:
   - "3000:3000"
  volumes:
   - grafana_data:/var/lib/grafana
   - ./grafana/provisioning/:/etc/grafana/provisioning/
   - ./grafana/dashboards/:/var/lib/grafana/dashboards/
  networks:
   - teleg

volumes:
 grafana_data: {}
 influxdb_data: {}

networks:
 teleg: